export enum PERMISSION_CODE {
  USER_MODULE = 'user_module',
  BUSINESS_USER_MANAGER = 'business_user_manager',
  USER_MANAGER = 'user_manager',
  ROLE_MANAGER = 'role_manager',
  AUDIT_MODULE = 'audit_module',
  AUDIT_LIST = 'business_task_audit',
  INCIDENT_AUDIT = 'incident_audit',
  TASK_MANAGER = 'task_manager',
  TASK_LIST = 'list_task',
  TASK_DETAIL = 'task_detail',
  LIST_CLUE = 'list_clue',
  LIST_HANDLER = 'list_handler',
  EXTERNAL_COMPANY_MODULE = 'external_company_module',
  COMPANY_LIST = 'get_all_companies',
  STORE_LIST = 'get_all_stores',
  TAG_MODULE = 'tag_module',
  TAG_GROUP = 'tag_group_module',
  TAG_LIST = 'tag_item_module',
  CODE_MODULE = 'code_module',
  INVITATION_GENERATE = 'invitation_gen',
  DEVICE_MODULE = 'device_module',
  DEVICE_RECORD_MODULE = 'device_record_module',
  DEVICE_RELATION_MODULE = 'device_relation_module',
  BUSSINESS_DEVICE_MODULE = 'business_device_info_module',
  OTA_MODULE = 'ota_module',
}
